[package]
name = "sift-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
fast_image_resize = { version = "6.1.0", features = ["image"] }
image = "0.25.10"
rayon = "1.12.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tract-onnx = "0.23.8"
